import Head from 'next/head';
import styled from 'styled-components';
import Navbar from '../components/Navbar';

const Hero=styled.div`
background: #fff;
height:90vh;
display: flex ;
justify-content:center
align-items: center;
`;

const Heading=styled.h1`
color:#000;
font-size: 2rem;
font-weight:900;
`;

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero>
      <Heading>
          Bienvenue sur notre site vous allez ici voir toutes ses caractéristiques.<br>
          </br>
          Ici vous serez capable de vous renseignez sur toutes nos offres en rapport avec l'univers de la science <br></br>
          Si vous êtes rêveur et que vous voulez décrocher la lune alors vous êtes au bon endroit<br></br><br></br>
          Que les étoiles vous fassent briller !!
      </Heading>
    </Hero>
    </>
  )
}
