import Head from 'next/head'
import styled from 'styled-components';

import Navbar from '../components/Navbar'

const Hero=styled.div`
background: #fff;
height:90vh;
display: flex ;
justify-content:center
align-items: center;
`;

const Heading=styled.h1`
color:#000;
font-size: 2rem;
font-weight:900;
`;

let db = {
  articles: [
    {
      système_solaire: "EXV65",
      nom: "fuerza 94",
      type: "soleil",
      température: "200 ",
      prix: "800M $",
      articleId: "1" ,
    },
    {
      système_solaire: "FDFI78",
      nom: "chicha94",
      type: "gazeuse",
      température: "21 ",
      prix: "10M $",
      articleId:"2",
    }
    // ...
  ],
  comments: [
    {
      id: "9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d",
      timestamp: 1664835049,
      content: "Content of the comment.",
      articleId: "6ec0bd7f-11c0-43da-975e-2a8ad9ebae0b",
      author: "Bob McLaren",
    },
    // ...
  ],
};

export default function About() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <Hero>
        <Heading>
          <div>
            Nous allons vous montrer nos planètes à vendre sur le dark système :

            <h1>fuerza 94</h1>
                <ul>
                    <li><a>système_solaire : EXV65 </a></li>
                    <li><a>type : soleil</a></li>
                    <li><a>température : 200 degré celcius</a></li>
                    <li><a>prix : 800M $</a></li>
                </ul>
            <h1>chicha94</h1>
                <ul>
                    <li><a>système_solaire : FDFI78 </a></li>
                    <li><a>type : gazeuse</a></li>
                    <li><a>température : 21 degré celcius</a></li>
                    <li><a>prix : 10M $</a></li>
                </ul>
          </div>
        </Heading>
       </Hero>
    </>
  )
}
